### ISSUE TITLE
LDAP: Allow to configure multiple accountBase and groupBase values

### ISSUE THREAD

**Issue by dpursehouse** [kbrebanov/ansible-gerrit#15]
In the current template it's only possible to configure a single value for the `accountBase` and `groupBase` entries under the `[ldap]` section.

The documentation of [groupBase](https://gerrit-review.googlesource.com/Documentation/config-gerrit.html#ldap.groupBase) and [accountBase](https://gerrit-review.googlesource.com/Documentation/config-gerrit.html#ldap.accountBase) doesn't mention it, but in fact these options may be repeated, for example:

```
[ldap]
        accountBase = OU=Europe,DC=example,DC=net
        accountBase = OU=America,DC=example,DC=net
        accountBase = OU=Asia,DC=example,DC=net
```

**Comment by dpursehouse** [comment]
I haven't started working on this yet because I'm not sure what's the best way.  Currently `gerrit_ldap_account_base` and `gerrit_ldap_group_base` are strings, but to support multiple values they'll need to be lists.  Should it just be changed to accept lists, or should it be made backward compatible for existing playbooks that set a string?

**Comment by kbrebanov** [comment]
@dpursehouse Maybe it's time to start using versioning and a changelog for this role...

**Comment by dpursehouse** [comment]
@kbrebanov yes, that would probably be a good idea.

**Comment by tkanemoto** [comment]
This can be achieve with PR #23

**Comment by kbrebanov** [comment]
This Ansible role is no longer being maintained.
