### ISSUE TITLE
LDAP: Allow to configure localUsernameToLowerCase

### ISSUE THREAD

**Issue by dpursehouse** [kbrebanov/ansible-gerrit#19]
When not specified, the default value of `ldap.localUsernameToLowerCase` is false.  It should be possible to configure it to true.

**Comment by dpursehouse** [comment]
I have a patch.

**Comment by tkanemoto** [comment]
This can be achieved with PR #23

**Comment by kbrebanov** [comment]
This Ansible role is no longer being maintained.
