### ISSUE TITLE
Use the ini_file module instead of templating the gerrit.config and secure.config files?

### ISSUE THREAD

**Issue by dpursehouse** [kbrebanov/ansible-gerrit#20]
Gerrit has a [huge amount of configuration options](https://gerrit-review.googlesource.com/Documentation/config-gerrit.html), and to support all of these in the role will make the templates quite large and complex.

Would it make things easier to use the [ini_file module](http://docs.ansible.com/ansible/ini_file_module.html) instead of templates?

**Comment by dpursehouse** [comment]
Or, instead of using `ini_file`, use the `command` module to invoke `git config` to add the settings.

**Comment by kbrebanov** [comment]
@dpursehouse I probably would continue using templates.

Probably use separate template files and use jinja2 'lookup' in the main template file to include each one.
Something like this: http://tureus.github.io/devops/2015/08/28/ansible-compiling-conf.d-pattern.html

**Comment by dpursehouse** [comment]
@kbrebanov another possibility would be to have something like `extra_config` which would allow the user to append any arbitrary settings on the end of the file.

This would allow to configure settings that are not commonly used, and also allow to configure new settings before support for them is added in the template.

**Comment by kbrebanov** [comment]
This Ansible role is no longer being maintained.
