### ISSUE TITLE
Need to install bouncy castle so gerrit works with SSH 7.0

### ISSUE THREAD

**Issue by SpamapS** [kbrebanov/ansible-gerrit#25]
https://code.google.com/p/gerrit/issues/detail?id=3517

SSH 7.0 has dropped insecure algorithms and Gerrit's default implementation doesn't have any secure ones. We just need to add bouncy castle libraries to make Gerrit pick that up and use a secure one.

The symptom (seen from Ubuntu 16.04) is as such:

Unable to negotiate with <GERRIT HOST> port 29418: no matching key exchange method found. Their offer: diffie-hellman-group1-sha1

**Comment by kbrebanov** [comment]
This Ansible role is no longer being maintained.
