### ISSUE TITLE
Rerun of the role fails

### ISSUE THREAD

**Issue by zaro0508** [kbrebanov/ansible-gerrit#27]
Running this role multiple times causes failure on reindex because Gerrit is already running.  The instance needs to be stopped before doing the reindex.

my ansible role:

```
roles:
 - { role: kbrebanov.gerrit, gerrit_version: 2.13.2, gerrit_sha256sum: c732cdcce183f50cfe49895658226988b3d0f0d91b5804d279920fae10e12aa7}
```

steps to repro:
1. run the role once -- Note, it run without failure.
2. run it again, fails on the reindex part

Here is the failure..

TASK [kbrebanov.gerrit : Reindexing Gerrit] ************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["java", "-jar", "/opt/gerrit/gerrit.war", "reindex", "-d", "/var/gerrit"], "delta": "0:00:07.755550", "end": "2016-10-26 20:54:21.338659", "failed": true, "rc": 128, "start": "2016-10-26 20:54:13.583109", "stderr": "fatal: DbInjector failed\nfatal: Unable to determine SqlDialect\nfatal:   caused by org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (Database may be already in use: \"Locked by another process\". Possible solutions: close all other connection(s); use the server mode [90020-176])\nfatal:   caused by org.h2.jdbc.JdbcSQLException: Database may be already in use: \"Locked by another process\". Possible solutions: close all other connection(s); use the server mode [90020-176]", "stdout": "", "stdout_lines": [], "warnings": []}

**Comment by kbrebanov** [comment]
This Ansible role is no longer being maintained.
