### ISSUE TITLE
ServerId auto-generated

### ISSUE THREAD

**Issue by lucamilanesio** [kbrebanov/ansible-gerrit#28]
The gerrit.config template is missing the serverId variable.

Example:
```ini
[gerrit]
  serverId = d5d70762-12d0-45a1-890d-524b12d3f735
```

That would break Gerrit 2.15 where the serverId is *very important* because is stored in the reviews in NoteDb. An  newly auto-generated serverId would break existing setups.

**Comment by dpursehouse** [comment]
Is this project maintained any more @kbrebanov ?  The last commits are more than 2 years ago, and there are still PRs from 2 years ago open.

**Comment by kbrebanov** [comment]
I haven't had a use for this role since 2 years ago so I have not been updating/maintaining it.

**Comment by lucamilanesio** [comment]
@kbrebanov anything against re-hosting on https://gerrit-review.googlesource.com and adding more maintainers for this project? It seems that your project has inspired many uses in the community and we may need to have an __official__ Ansible packaging for Gerrit.

Could you re-release the code under the Apache 2.0 License?

**Comment by kbrebanov** [comment]
This Ansible role is no longer being maintained.
