### ISSUE TITLE
Why is $site/bin/gerrit.sh templated in the gerrit role?

### ISSUE THREAD

**Issue by dpursehouse** [kbrebanov/ansible-gerrit#3]
The gerrit.sh file is included in the gerrit.war and gets put into $site/bin when the init command is run.

The template doesn't use any variables and apart from a couple of whitespace diffs is the same as in the latest master branch of gerrit.  As we can see [in this query on gerrit-review](https://gerrit-review.googlesource.com/#/q/status:merged+file:gerrit.sh) the file doesn't change very often, but if it does, templating it like this will mean it doesn't get updated unless also updated here when moving to a later version of Gerrit.

So I just wanted to check if there's an other reason for templating it, before I do a PR to remove it?

**Comment by kbrebanov** [comment]
@dpursehouse We can remove the template for gerrit.sh and use the one that gets generated when running init.
