### ISSUE TITLE
Site cannot be reinitialized by running the play again

### ISSUE THREAD

**Issue by dpursehouse** [kbrebanov/ansible-gerrit#5]
After the play has been run once, the init will not run again on subsequent runs of the play because the `bin` folder already exists:

```
 "stdout": "skipped, since /var/gerrit/bin exists"
```

**Comment by kbrebanov** [comment]
@dpursehouse With this modification, would Gerrit be re-initialized on each run? If so, maybe we could have a variable to decide if we want to re-initialize or not...

**Comment by dpursehouse** [comment]
@kbrebanov yes, it will re-initialize on each run, which is not ideal, but better than not re-initializing at all.  

I'd prefer not to introduce a variable that needs to be set.  It would be better if it could be determined based on changes to the inputs.  I'll see if I can figure out how to make it do that.

**Comment by dpursehouse** [comment]
@kbrebanov Please try again with 02765c0e0d5d81ccad52bb00c09bac11dc76906e

**Comment by kbrebanov** [comment]
@dpursehouse LTGM.

If you can modify all the **init_options** variables to **gerrit_init_options**, I'll merge afterwards.
The actual filename in the _tmp_ folder can still be named **init_options**.

**Comment by dpursehouse** [comment]
> modify all the _init_options_ variables to _gerrit_init_options_

Done in 7ab2565a8a0524dcb204b2175a927feccfa45934
